datasource.url=jdbc:mysql://localhost:3306/digital-document-approval-system_dbspring
spring.datasource.username=root
spring.datasource.password=divyagujar12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8080

jwt.secret=yourBase64SecretKeyHereYourBase64SecretKeyHereYourBase64SecretKeyHere
jwt.expiration=86400000
file.upload.dir=uploads/
